# Cargar las librerias

In [21]:
import pandas as pd

# Cargar los datos

In [22]:
url = "https://raw.githubusercontent.com/ElenaVillano/databases/refs/heads/main/db_falsas_alarmas.csv"
df = pd.read_csv(url)
df.head(1)

,folio,fecha_hora_creacion,fecha_hora_cierre,tipo_incidente_c4,incidente_c4,alcaldia_inicio,codigo_cierre,clas_con_f_alarma,tipo_entrada,alcaldia_cierre,alcaldia_catalogo,colonia_catalogo,longitud,latitud
0,C5/20220923/04016,2022-09-23 18:38:34,2022-09-23 22:22:27,Accidente,Choque sin lesionados,VENUSTIANO CARRANZA,A,EMERGENCIA,LLAMADA DEL 911,VENUSTIANO CARRANZA,Venustiano Carranza,20 De Noviembre,-99.108352,19.44392

# 5.1 Contexto y estructura
**¿Qué fenómeno registra la base? ¿Quién la produjo y con qué propósito?**
Fuente de los datos y objetivo del análisis: La fuente Incidentes viales reportados por C5 del gobierno de la CDMX, el objetivo del análisis es contar con una visión general del tipo de indicentes que se reportan, desde qué medios y alcaldías. Así como cuanto se tardan en responder y si existen patrones temporales.

**¿Cuántas filas y columnas tiene?**
La base de datos tiene aproximadamente 124.3 mil filas y 14 columnas
¿Qué significa cada variable? Descríbanla con sus propias palabras, apoyándose en el diccionario de datos.

**Columnas**

**folio**: identificador que nos permite contabilizar todos los incidentes que se reportan aunque no necesariamente hagan referencia a incidentes distintos, ya que un incidente puede estar reportado más de una vez

**fecha_hora_creacion**: fecha exacta en la que se generó el reporte

**fecha_hora_cierre**: fecha en la que se concluyó la atención del reporte y se registró en el sistema

**tipo_incidente_c4**: Se reporta una categoría de accidente e.g. accidente, lesionado, "mi calle", "mi taxi", cadáver

**incidente_c4**: se agregan más detalles del incidente, e.g si hubo motociclistas, si fue un choque sin lesionados, etc.

**alcaldia_inicio**: alcaldía donde ocurrió el incidente

**codigo_cierre**: Es una clasificación que divide cada incidente en cuatro letras {A,F,D,I} y se refieren a A = “Afirmativo” F = “Falso” D = “Duplicados” I = “Informativo”

**clas_con_f_alarma**: Aqui se reportan las caterorias emergencia, unidades médicas, falsa alarma, delito, incidentes externos

**tipo_entrada**: Es el medio por el cuál se realiza el reporte del incidente

**alcaldia_cierre**: Es la alcaldía donde se da resolución al incidente

**alcaldia_catalogo**: Nombre de la alcaldía, aunque deberían ser 16 algunos registros vienen con na

**colonia_catalogo**: se incluyende los nombre de colonias

**longitud**: coordenadas de la longitud

**latitud**: coordenadas de la latitud

In [23]:
df.shape

(124261, 14)

In [24]:
df.columns

Index(['folio', 'fecha_hora_creacion', 'fecha_hora_cierre',
       'tipo_incidente_c4', 'incidente_c4', 'alcaldia_inicio', 'codigo_cierre',
       'clas_con_f_alarma', 'tipo_entrada', 'alcaldia_cierre',
       'alcaldia_catalogo', 'colonia_catalogo', 'longitud', 'latitud'],
      dtype='str')

In [25]:
df.dtypes

folio                      str
fecha_hora_creacion        str
fecha_hora_cierre          str
tipo_incidente_c4          str
incidente_c4               str
alcaldia_inicio            str
codigo_cierre              str
clas_con_f_alarma          str
tipo_entrada               str
alcaldia_cierre            str
alcaldia_catalogo          str
colonia_catalogo           str
longitud               float64
latitud                float64
dtype: object

In [26]:
df['folio'].unique()

<StringArray>
['C5/20220923/04016', 'C5/20220829/00630', 'C5/20220724/01907',
 'C5/20240215/03071', 'C5/20221006/03493', 'C5/20231028/05309',
 'C5/20231223/02004', 'C5/20221005/00842', 'C5/20220314/03482',
 'C5/20220328/01491',
 ...
 'C5/20220514/03527', 'C5/20221013/04486', 'C5/20220729/00291',
 'C5/20221002/05827', 'C5/20220721/04370', 'C5/20221205/01568',
 'C5/20221029/02927', 'C5/20231010/02137', 'C5/20230516/01380',
 'C5/20221114/03069']
Length: 124261, dtype: str

In [27]:
df['tipo_incidente_c4'].unique()

<StringArray>
[          'Accidente',           'Lesionado',            'Mi Calle',
             'Cadáver',               'Sismo',             'Mi Taxi',
 'Detención ciudadana']
Length: 7, dtype: str

In [28]:
df['incidente_c4'].unique()

<StringArray>
[           'Choque sin lesionados',                     'Motociclista',
            'Choque con lesionados',                      'Atropellado',
          'Vehículo atrapadovarado',             'Choque con prensados',
 'Persona atrapada / desbarrancada',                         'Ciclista',
                        'Volcadura',                      'Ferroviario',
            'Incidente de tránsito',                            'Otros',
        'Accidente automovilístico',           'Vehiculo desbarrancado',
                        'Monopatín',              'Persona atropellada']
Length: 16, dtype: str

In [29]:
df['codigo_cierre'].unique()

<StringArray>
['A', 'F', 'D', 'I']
Length: 4, dtype: str

In [30]:
df['clas_con_f_alarma'].unique()

<StringArray>
[         'EMERGENCIA',   'URGENCIAS MEDICAS',        'FALSA ALARMA',
              'DELITO', 'INCIDENTES EXTERNOS']
Length: 5, dtype: str

In [31]:
df['tipo_entrada'].unique()

<StringArray>
[ 'LLAMADA DEL 911',            'RADIO', 'BOTÓN DE AUXILIO',
            'REDES',      'APLICATIVOS',           'CÁMARA',
   'LLAMADA APP911']
Length: 7, dtype: str

In [32]:
df['alcaldia_catalogo'].unique()

<StringArray>
[   'Venustiano Carranza',             'Cuauhtémoc',             'Iztapalapa',
 'La Magdalena Contreras',         'Miguel Hidalgo',              'Iztacalco',
      'Gustavo A. Madero',         'Álvaro Obregón',                'Tlalpan',
               'Coyoacán',          'Benito Juárez',             'Xochimilco',
  'Cuajimalpa de Morelos',           'Azcapotzalco',                'Tláhuac',
             'Milpa Alta',                      nan]
Length: 17, dtype: str

In [33]:
df['colonia_catalogo'].unique()

<StringArray>
[                               '20 De Noviembre',
                                         'Obrera',
                           'San Andres Tetepilco',
                                        'La Cruz',
                    'Santa Martha Acatitla Norte',
                                   'La Esperanza',
                             'Anahuac Ii Seccion',
                              'Agricola Oriental',
                            'San Jeronimo Lidice',
                                        'Federal',
 ...
               'Movimiento Organizado De Tlalpan',
 'Barrio Tetitla Del Pueblo Santa Cruz Acalpixca',
                           'Valle De Santa Maria',
                                      'Tempiluli',
                                   'La Milagrosa',
              'Pueblo Santa Catarina Yecahuizotl',
                              'Hacienda San Juan',
                             'Santisima Trinidad',
                           'Ampliacion Arboledas',
                           'Ampliacion Acueducto']
Length: 1374, dtype: str

# 5.2. Entidades y eventos 
**¿Cuál es la unidad de observación de cada fila?**
La unidad de análisis es cada reporte que se realiza

**¿Cuáles son las entidades relevantes y cómo se identifican?**

Las principales entidades de la base de datos son los reportes de incidentes, los tipos de incidentes, las ubicaciones geográficas y los mecanismos de reporte. Cada registro se identifica mediante un folio único, mientras que las variables tipo_incidente_c4 e incidente_c4 permiten clasificar la naturaleza del evento.

**¿Qué eventos aparecen y qué representan respecto de esas entidades?**

Los eventos aparecen en la columna codigo_cierre ya que ahí se registra si el incidente fue verdadero o no, entre otros casos

**¿Un folio identifica necesariamente un evento real distinto. Reflexionen sobre los duplicados**
Los folios no necesariamente identifican a un evento distinto ya que cada folio nuevo se genera cuando se realiza un reporte, el cual puede originarse de un evento repetido. La columna codigo_cierre nos ayudará a reconocer los folios que sí hacen referencia a un incidente distinto.

In [34]:
## Número de filas 
len(df['folio'])

124261

In [35]:
## Númeo de folios unicos
len(df['folio'].unique())

124261

# 5.3 Tipos, calidad y limpieza
**Identifiquen tipos de datos y valores faltantes**
Todos los objetos se encuentran en formato str a excepción de latitud y longitud que son formato float 

**Revisen si las variables están representadas correctamente, especialmente fechas y horas**
No están bien representadas porque se encuentran en formato string.

**Hagan las conversiones necesarias y expliquen cada decisión**
Es necesario coercionar el tipo de valor a formato de fecha_hora_creacion y fecha_hora_cierre.

**Identifiquen posibles duplicados, categorías inconsistentes o coordenadas fuera del rango esperado, cuando aplique**
No identificamos valores duplicados en los folios. Sin embargo, los valores no son 100% consistentes dado que varían en el largo de la cadena de texto. Por ejemplo, algunos contienen 16 dígitos y otros 15 o 19. 

Asimismo, se detectaron 4 puntos fuera de la Ciudad de México.

**Coordenadas fuera del rango esperado**

De acuerdo con el INEGI las cordenadas correspondientes a la CDMX son Longitud99°21'53.64" W 98°56'25.08" W, Latitud19°02'53.52" N 19°35'34.08" N

Utilizando esta fórmula 

$$
G + \frac{M}{60} + \frac{S}{3600}
$$

tenemos que los rangos que deberían estar dentro del polígono son Longitud: -99.3649 a -98.9403 Latitud: 19.0482 a 19.5928

Con esta información se pueden rectificar los datos que no corresponde a incidentes ocurridos en la CDMX. Por otro lado, la variable alcaldia_catalogo presenta valores faltantes, de acuerdo con https://datos.cdmx.gob.mx/dataset carpetas-de-investigacion-fgj-de-la-ciudad-de-mexico 

A partir de diciembre de 2023 se incluyeron las columnas "colonia_catalogo" y "alcaldia_catalogo". Estos campos se generaron a partir del cruce de la georreferenciación (latitud y longitud) y si analizamos los ausentes de dicha columa podemos ver que los faltantes estan presentes entre 2022 y 2024 por lo que se podrían completar con la información de la latitud y longitud https://en.www.inegi.org.mx/contenidos/app/areasgeograficas/resumen/resumen_09.pdf página 6

In [36]:
df.dtypes

folio                      str
fecha_hora_creacion        str
fecha_hora_cierre          str
tipo_incidente_c4          str
incidente_c4               str
alcaldia_inicio            str
codigo_cierre              str
clas_con_f_alarma          str
tipo_entrada               str
alcaldia_cierre            str
alcaldia_catalogo          str
colonia_catalogo           str
longitud               float64
latitud                float64
dtype: object

In [37]:
## Identificación de faltantes
columnas = df.columns

In [38]:
for columna in columnas:
    print (columna + " : "+  str(df[columna].isna().sum()))

folio : 0
fecha_hora_creacion : 0
fecha_hora_cierre : 0
tipo_incidente_c4 : 0
incidente_c4 : 0
alcaldia_inicio : 8
codigo_cierre : 0
clas_con_f_alarma : 0
tipo_entrada : 0
alcaldia_cierre : 8
alcaldia_catalogo : 130
colonia_catalogo : 2718
longitud : 0
latitud : 0

In [39]:
## Corrección de las fechas 
df['fecha_hora_creacion'] = pd.to_datetime(df['fecha_hora_creacion'],format='%Y-%m-%d %H:%M:%S')

In [40]:
df['fecha_hora_cierre'] = pd.to_datetime(df['fecha_hora_cierre'],format='%Y-%m-%d %H:%M:%S')

In [41]:
## Verificar que todos los folios seas válidos
#df['folio'].astype(str).str.len().nunique()
df['largo'] = df['folio'].astype(str).str.len()
#df['folio'].astype(str).str.len().value_counts().sort_index()

In [42]:
df['largo'].value_counts().sort_index()

largo
15        91
17    116919
18      7251
Name: count, dtype: int64

In [43]:
df[df['largo']==15].head(2)

,folio,fecha_hora_creacion,fecha_hora_cierre,tipo_incidente_c4,incidente_c4,alcaldia_inicio,codigo_cierre,clas_con_f_alarma,tipo_entrada,alcaldia_cierre,alcaldia_catalogo,colonia_catalogo,longitud,latitud,largo
310,C5/220322/00023,2022-03-22 00:28:21,2022-03-22 00:37:10,Mi Calle,Incidente de tránsito,GUSTAVO A. MADERO,F,FALSA ALARMA,APLICATIVOS,GUSTAVO A. MADERO,Gustavo A. Madero,San Juan De Aragon Vi Seccion,-99.067994,19.465618,15
445,C5/220313/00238,2022-03-13 03:28:32,2022-03-13 03:40:21,Mi Calle,Incidente de tránsito,IZTAPALAPA,F,FALSA ALARMA,APLICATIVOS,IZTAPALAPA,Iztapalapa,Barrio La Asuncion,-99.093631,19.365590,15

In [44]:
df[df['largo']==18].head(2)

,folio,fecha_hora_creacion,fecha_hora_cierre,tipo_incidente_c4,incidente_c4,alcaldia_inicio,codigo_cierre,clas_con_f_alarma,tipo_entrada,alcaldia_cierre,alcaldia_catalogo,colonia_catalogo,longitud,latitud,largo
34,C2O/20230324/00114,2023-03-24 14:17:35,2023-03-24 17:19:18,Lesionado,Atropellado,TLAHUAC,D,URGENCIAS MEDICAS,BOTÓN DE AUXILIO,TLAHUAC,Tláhuac,San Isidro,-99.01138,19.25573,18
44,C2S/20221022/00156,2022-10-22 23:35:45,2022-10-23 02:48:25,Accidente,Choque sin lesionados,COYOACAN,D,EMERGENCIA,BOTÓN DE AUXILIO,COYOACAN,Coyoacán,Olimpica,-99.16954,19.30569,18

In [45]:
df[df['largo']==17].head(2)

,folio,fecha_hora_creacion,fecha_hora_cierre,tipo_incidente_c4,incidente_c4,alcaldia_inicio,codigo_cierre,clas_con_f_alarma,tipo_entrada,alcaldia_cierre,alcaldia_catalogo,colonia_catalogo,longitud,latitud,largo
0,C5/20220923/04016,2022-09-23 18:38:34,2022-09-23 22:22:27,Accidente,Choque sin lesionados,VENUSTIANO CARRANZA,A,EMERGENCIA,LLAMADA DEL 911,VENUSTIANO CARRANZA,Venustiano Carranza,20 De Noviembre,-99.108352,19.443920,17
1,C5/20220829/00630,2022-08-29 02:56:31,2022-08-29 06:04:53,Accidente,Motociclista,CUAUHTEMOC,A,URGENCIAS MEDICAS,LLAMADA DEL 911,CUAUHTEMOC,Cuauhtémoc,Obrera,-99.140843,19.416669,17

In [46]:
#.value_counts().sort_index()
df['tipo_incidente_c4'].value_counts().sort_index()

tipo_incidente_c4
Accidente              110888
Cadáver                   245
Detención ciudadana        97
Lesionado               12906
Mi Calle                   83
Mi Taxi                    13
Sismo                      29
Name: count, dtype: int64

In [47]:
df['incidente_c4'].value_counts().sort_index()

incidente_c4
Accidente automovilístico             206
Atropellado                         13042
Choque con lesionados               36245
Choque con prensados                  241
Choque sin lesionados               56845
Ciclista                             1560
Ferroviario                            22
Incidente de tránsito                  96
Monopatín                              53
Motociclista                        12374
Otros                                  68
Persona atrapada / desbarrancada      681
Persona atropellada                     5
Vehiculo desbarrancado                 64
Vehículo atrapadovarado               543
Volcadura                            2216
Name: count, dtype: int64

In [48]:
df['alcaldia_inicio'].value_counts().sort_index()

alcaldia_inicio
ALVARO OBREGON             8453
AZCAPOTZALCO               5179
BENITO JUAREZ              8929
COYOACAN                   9113
CUAJIMALPA DE MORELOS      2340
CUAUHTEMOC                12924
GUSTAVO A. MADERO         13876
IZTACALCO                  5983
IZTAPALAPA                20199
LA MAGDALENA CONTRERAS     1954
MIGUEL HIDALGO             7663
MILPA ALTA                  867
TLAHUAC                    3656
TLALPAN                    9065
VENUSTIANO CARRANZA        9213
XOCHIMILCO                 4839
Name: count, dtype: int64

In [49]:
df['clas_con_f_alarma'].value_counts().sort_index()

clas_con_f_alarma
DELITO                    97
EMERGENCIA             60772
FALSA ALARMA              32
INCIDENTES EXTERNOS        5
URGENCIAS MEDICAS      63355
Name: count, dtype: int64

In [50]:
df['tipo_entrada'].value_counts().sort_index()

tipo_entrada
APLICATIVOS            126
BOTÓN DE AUXILIO      6998
CÁMARA                 332
LLAMADA APP911          15
LLAMADA DEL 911     111287
RADIO                 5312
REDES                  191
Name: count, dtype: int64

In [51]:
df['alcaldia_cierre'].value_counts().sort_index()

alcaldia_cierre
ALVARO OBREGON             8481
AZCAPOTZALCO               5188
BENITO JUAREZ              8917
COYOACAN                   9111
CUAJIMALPA DE MORELOS      2333
CUAUHTEMOC                12911
GUSTAVO A. MADERO         13850
IZTACALCO                  5989
IZTAPALAPA                20197
LA MAGDALENA CONTRERAS     1948
MIGUEL HIDALGO             7673
MILPA ALTA                  869
TLAHUAC                    3656
TLALPAN                    9070
VENUSTIANO CARRANZA        9229
XOCHIMILCO                 4831
Name: count, dtype: int64

In [52]:
df['alcaldia_catalogo'].value_counts().sort_index()

alcaldia_catalogo
Azcapotzalco               5161
Benito Juárez              8937
Coyoacán                   9144
Cuajimalpa de Morelos      2347
Cuauhtémoc                12902
Gustavo A. Madero         13812
Iztacalco                  5869
Iztapalapa                20145
La Magdalena Contreras     1874
Miguel Hidalgo             7828
Milpa Alta                  863
Tlalpan                    9069
Tláhuac                    3613
Venustiano Carranza        9301
Xochimilco                 4882
Álvaro Obregón             8384
Name: count, dtype: int64

In [53]:
df['colonia_catalogo'].value_counts().sort_index()

colonia_catalogo
10 De Abril              14
10 De Mayo               67
12 De Diciembre          18
15 De Agosto             56
16 De Septiembre         52
                       ...
Zentlapatl               46
Zona Centro             361
Zona Escolar             97
Zona Escolar Oriente     60
Zona Federal              6
Name: count, Length: 1373, dtype: int64

In [54]:
df['colonia_catalogo'].value_counts().sort_index()

colonia_catalogo
10 De Abril              14
10 De Mayo               67
12 De Diciembre          18
15 De Agosto             56
16 De Septiembre         52
                       ...
Zentlapatl               46
Zona Centro             361
Zona Escolar             97
Zona Escolar Oriente     60
Zona Federal              6
Name: count, Length: 1373, dtype: int64

In [55]:
### Varificación de la longitud y latitud
# Algunas cordenadas están fuera del internevalo

print(df['longitud'].min())
print(df['longitud'].max())
print(df['latitud'].max())
print(df['latitud'].min())

-99.3529144
-98.94794
19.6322009
19.094877

In [56]:
df['cordenada_fuera_cdmx'] = ~(df['latitud'].between(19.0482, 19.5928) &df['longitud'].between(-99.3649, -98.9403))

In [57]:
df['cordenada_fuera_cdmx'].value_counts().sort_index()

cordenada_fuera_cdmx
False    124257
True          4
Name: count, dtype: int64

In [58]:
df[df['cordenada_fuera_cdmx']==True]

,folio,fecha_hora_creacion,fecha_hora_cierre,tipo_incidente_c4,incidente_c4,alcaldia_inicio,codigo_cierre,clas_con_f_alarma,tipo_entrada,alcaldia_cierre,alcaldia_catalogo,colonia_catalogo,longitud,latitud,largo,cordenada_fuera_cdmx
26129,C5/220401/01123,2022-04-01 17:56:02,2022-04-01 17:59:04,Mi Calle,Incidente de tránsito,NaN,F,FALSA ALARMA,APLICATIVOS,NaN,NaN,NaN,-99.021432,19.632201,15,True
40950,C5/220401/01134,2022-04-01 17:56:25,2022-04-01 18:00:22,Mi Calle,Incidente de tránsito,NaN,F,FALSA ALARMA,APLICATIVOS,NaN,NaN,NaN,-99.021432,19.632201,15,True
59997,C5/220401/01137,2022-04-01 17:56:28,2022-04-01 17:59:48,Mi Calle,Incidente de tránsito,NaN,F,FALSA ALARMA,APLICATIVOS,NaN,NaN,NaN,-99.021432,19.632201,15,True
108069,C5/220401/01124,2022-04-01 17:56:05,2022-04-01 17:58:30,Mi Calle,Incidente de tránsito,NaN,F,FALSA ALARMA,APLICATIVOS,NaN,NaN,NaN,-99.021432,19.632201,15,True

In [59]:
## Considerando que solamente 
df_alcaldia_catalogo_faltante = df[df['alcaldia_catalogo'].isna()]

In [60]:
df_alcaldia_catalogo_faltante.columns

Index(['folio', 'fecha_hora_creacion', 'fecha_hora_cierre',
       'tipo_incidente_c4', 'incidente_c4', 'alcaldia_inicio', 'codigo_cierre',
       'clas_con_f_alarma', 'tipo_entrada', 'alcaldia_cierre',
       'alcaldia_catalogo', 'colonia_catalogo', 'longitud', 'latitud', 'largo',
       'cordenada_fuera_cdmx'],
      dtype='str')

In [61]:
df_alcaldia_catalogo_faltante['fecha_hora_creacion'].min()

Timestamp('2022-01-22 11:05:33')

In [62]:
df_alcaldia_catalogo_faltante['fecha_hora_creacion'].max()

Timestamp('2024-02-27 16:51:28')

In [63]:
df['alcaldia_inicio'].unique()

<StringArray>
[   'VENUSTIANO CARRANZA',             'CUAUHTEMOC',             'IZTAPALAPA',
 'LA MAGDALENA CONTRERAS',         'MIGUEL HIDALGO',              'IZTACALCO',
      'GUSTAVO A. MADERO',         'ALVARO OBREGON',                'TLALPAN',
               'COYOACAN',          'BENITO JUAREZ',             'XOCHIMILCO',
  'CUAJIMALPA DE MORELOS',           'AZCAPOTZALCO',                'TLAHUAC',
             'MILPA ALTA',                      nan]
Length: 17, dtype: str

In [64]:
df['alcaldia_cierre'].unique()

<StringArray>
[   'VENUSTIANO CARRANZA',             'CUAUHTEMOC',             'IZTAPALAPA',
 'LA MAGDALENA CONTRERAS',         'MIGUEL HIDALGO',              'IZTACALCO',
      'GUSTAVO A. MADERO',         'ALVARO OBREGON',                'TLALPAN',
               'COYOACAN',          'BENITO JUAREZ',             'XOCHIMILCO',
  'CUAJIMALPA DE MORELOS',           'AZCAPOTZALCO',                'TLAHUAC',
             'MILPA ALTA',                      nan]
Length: 17, dtype: str

In [65]:
df['alcaldia_catalogo'].unique()

<StringArray>
[   'Venustiano Carranza',             'Cuauhtémoc',             'Iztapalapa',
 'La Magdalena Contreras',         'Miguel Hidalgo',              'Iztacalco',
      'Gustavo A. Madero',         'Álvaro Obregón',                'Tlalpan',
               'Coyoacán',          'Benito Juárez',             'Xochimilco',
  'Cuajimalpa de Morelos',           'Azcapotzalco',                'Tláhuac',
             'Milpa Alta',                      nan]
Length: 17, dtype: str

In [66]:
set(df['alcaldia_inicio'].unique()) == set(df['alcaldia_cierre'].unique())

True

In [67]:
diccionario_alcaldias = {
    'VENUSTIANO CARRANZA': 'Venustiano Carranza',
    'CUAUHTEMOC': 'Cuauhtémoc',
    'IZTAPALAPA': 'Iztapalapa',
    'LA MAGDALENA CONTRERAS': 'La Magdalena Contreras',
    'MIGUEL HIDALGO': 'Miguel Hidalgo',
    'IZTACALCO': 'Iztacalco',
    'GUSTAVO A. MADERO': 'Gustavo A. Madero',
    'ALVARO OBREGON': 'Álvaro Obregón',
    'TLALPAN': 'Tlalpan',
    'COYOACAN': 'Coyoacán',
    'BENITO JUAREZ': 'Benito Juárez',
    'XOCHIMILCO': 'Xochimilco',
    'CUAJIMALPA DE MORELOS': 'Cuajimalpa de Morelos',
    'AZCAPOTZALCO': 'Azcapotzalco',
    'TLAHUAC': 'Tláhuac',
    'MILPA ALTA': 'Milpa Alta'
}

In [68]:
df['alcaldia_inicio']  = df['alcaldia_inicio'].map(diccionario_alcaldias)

In [69]:
df['alcaldia_cierre']  = df['alcaldia_cierre'].map(diccionario_alcaldias)

In [70]:
for columna in columnas:
    print (columna + " : "+  str(df[columna].isna().sum()))

folio : 0
fecha_hora_creacion : 0
fecha_hora_cierre : 0
tipo_incidente_c4 : 0
incidente_c4 : 0
alcaldia_inicio : 8
codigo_cierre : 0
clas_con_f_alarma : 0
tipo_entrada : 0
alcaldia_cierre : 8
alcaldia_catalogo : 130
colonia_catalogo : 2718
longitud : 0
latitud : 0

In [71]:
for columna in columnas:
    print (columna + " : "+  str(100*df[columna].isna().sum()/df.shape[0]))

folio : 0.0
fecha_hora_creacion : 0.0
fecha_hora_cierre : 0.0
tipo_incidente_c4 : 0.0
incidente_c4 : 0.0
alcaldia_inicio : 0.006438061821488641
codigo_cierre : 0.0
clas_con_f_alarma : 0.0
tipo_entrada : 0.0
alcaldia_cierre : 0.006438061821488641
alcaldia_catalogo : 0.10461850459919042
colonia_catalogo : 2.187331503850766
longitud : 0.0
latitud : 0.0

In [72]:
sum(df['alcaldia_cierre'] != df['alcaldia_inicio'])

756

# 5.4. Data Profiling o perfilado por tipo de variable 

**Categóricas**: categorías, frecuencias y valores faltantes. 

**Numéricas**: medidas descriptivas y valores extremos, si existen. 

**Temporales:** fechas mínima y máxima, cobertura y granularidad. 

**Interpretación de los resultados**

La base de datos contiene siete variables categóricas, con entre 4 y 16 categorías únicas.

**En tipo_incidente_c4**, predominan los accidentes (89.14%), seguidos de los reportes de lesionados (10.50%), mientras que las demás categorías tienen una participación marginal.

**En incidente_c4**, los choques sin lesionados (46.12%) y con lesionados (29.02%) concentran el 75.14% de los registros. Les siguen los atropellamientos (10.60%) y los incidentes relacionados con motociclistas (9.89%).

En general, se observa una alta concentración de los reportes en accidentes vehiculares, particularmente choques.

**En codigo_cierre**, predominan los registros clasificados como D, es decir duplicado, (42.57%), seguidos de A (36.54%) y F (20.22%). Por su parte, la categoría I (0.67%) presenta la menor frecuencia. Esto evidencia una proporción importante de reportes clasificados como duplicados.

**En clas_con_f_alarma**, predominan los reportes clasificados como Urgencias médicas (50.86%) y Emergencia (49.04%), que en conjunto concentran el 99.90% de los registros. Por su parte, las categorías Delito, Falsa alarma e Incidentes externos presentan una participación marginal.

**En tipo_entrada**, predominan los reportes recibidos mediante llamadas al 911 (89.47%), seguidos del botón de auxilio (5.70%) y radio (4.29%). Los demás medios de entrada presentan una participación marginal, lo que evidencia que las llamadas al 911 constituyen el principal canal de reporte de incidentes en la CDMX.

Para las numéricas el tiempo_minutos registra un promedio de 263.70 minutos, con una mediana de 187.63 minutos. La desviación estándar de 300.54 minutos y el valor máximo de 4,600.17 minutos sugieren la presencia de valores extremos y una distribución sesgada hacia la derecha. Esto indica que algunos incidentes presentan tiempos de cierre considerablemente superiores a los habituales.

**Las variables fecha_hora_creacion y fecha_hora_cierre** presentan una cobertura temporal de diciembre de 2021 a febrero de 2024, con registros a nivel de segundos y sin valores faltantes. Esto permite analizar la evolución de los incidentes y sus tiempos de atención a lo largo del periodo.

In [96]:
### Creación de variables para más análisis 

df['hora'] = df['fecha_hora_creacion'].dt.hour
df['dia'] = df['fecha_hora_creacion'].dt.day
df['mes'] = df['fecha_hora_creacion'].dt.month
df['año'] = df['fecha_hora_creacion'].dt.year
df['tiempo_minutos'] = (df['fecha_hora_cierre'] - df['fecha_hora_creacion']).dt.total_seconds() / 60

In [97]:
dias = { 0: 'Lunes',1: 'Martes',2: 'Miércoles',3: 'Jueves',4: 'Viernes',5: 'Sábado',6: 'Domingo'}
df['dia_semana'] = (df['fecha_hora_creacion'].dt.dayofweek.map(dias))

/var/folders/56/svp2dnsn1jx5mpmlp_7j_z4m0000gn/T/ipykernel_2036/3185948165.py:2: Pandas4Warning: Series.dt.dayofweek is deprecated and will be removed in a future version. Use Series.dt.day_of_week instead.
  df['dia_semana'] = (df['fecha_hora_creacion'].dt.dayofweek.map(dias))

In [98]:
df.columns

Index(['folio', 'fecha_hora_creacion', 'fecha_hora_cierre',
       'tipo_incidente_c4', 'incidente_c4', 'alcaldia_inicio', 'codigo_cierre',
       'clas_con_f_alarma', 'tipo_entrada', 'alcaldia_cierre',
       'alcaldia_catalogo', 'colonia_catalogo', 'longitud', 'latitud', 'largo',
       'cordenada_fuera_cdmx', 'hora', 'dia', 'mes', 'año', 'dia_semana',
       'tiempo_minutos'],
      dtype='str')

In [99]:
variables_categoricas = ['tipo_incidente_c4','incidente_c4','alcaldia_inicio','codigo_cierre','clas_con_f_alarma',
'tipo_entrada','alcaldia_cierre']

# **Identificar el número de categorías**

In [100]:
def tabla_frecuencias(df, columna):
    tabla = (df[columna].value_counts().reset_index())
    tabla.columns = ['categoria', 'frecuencia']
    tabla['porcentaje'] = (
        100 * tabla['frecuencia'] / df.shape[0]).round(2)

    return tabla

In [102]:
print(variables_categoricas[0])
print(tabla_frecuencias(df,variables_categoricas[0]))

tipo_incidente_c4
             categoria  frecuencia  porcentaje
0            Accidente      110888       89.24
1            Lesionado       12906       10.39
2              Cadáver         245        0.20
3  Detención ciudadana          97        0.08
4             Mi Calle          83        0.07
5                Sismo          29        0.02
6              Mi Taxi          13        0.01

In [103]:
print(variables_categoricas[1])
print(tabla_frecuencias(df,variables_categoricas[1]))

incidente_c4
                           categoria  frecuencia  porcentaje
0              Choque sin lesionados       56845       45.75
1              Choque con lesionados       36245       29.17
2                        Atropellado       13042       10.50
3                       Motociclista       12374        9.96
4                          Volcadura        2216        1.78
5                           Ciclista        1560        1.26
6   Persona atrapada / desbarrancada         681        0.55
7            Vehículo atrapadovarado         543        0.44
8               Choque con prensados         241        0.19
9          Accidente automovilístico         206        0.17
10             Incidente de tránsito          96        0.08
11                             Otros          68        0.05
12            Vehiculo desbarrancado          64        0.05
13                         Monopatín          53        0.04
14                       Ferroviario          22        0.02
15               Persona atropellada           5        0.00

In [104]:
print(variables_categoricas[2])
print(tabla_frecuencias(df,variables_categoricas[2]))

alcaldia_inicio
                 categoria  frecuencia  porcentaje
0               Iztapalapa       20199       16.26
1        Gustavo A. Madero       13876       11.17
2               Cuauhtémoc       12924       10.40
3      Venustiano Carranza        9213        7.41
4                 Coyoacán        9113        7.33
5                  Tlalpan        9065        7.30
6            Benito Juárez        8929        7.19
7           Álvaro Obregón        8453        6.80
8           Miguel Hidalgo        7663        6.17
9                Iztacalco        5983        4.81
10            Azcapotzalco        5179        4.17
11              Xochimilco        4839        3.89
12                 Tláhuac        3656        2.94
13   Cuajimalpa de Morelos        2340        1.88
14  La Magdalena Contreras        1954        1.57
15              Milpa Alta         867        0.70

In [105]:
print(variables_categoricas[3])
print(tabla_frecuencias(df,variables_categoricas[3]))

codigo_cierre
  categoria  frecuencia  porcentaje
0         D       52963       42.62
1         A       45189       36.37
2         F       25219       20.30
3         I         890        0.72

In [106]:
print(variables_categoricas[4])
print(tabla_frecuencias(df,variables_categoricas[4]))

clas_con_f_alarma
             categoria  frecuencia  porcentaje
0    URGENCIAS MEDICAS       63355       50.99
1           EMERGENCIA       60772       48.91
2               DELITO          97        0.08
3         FALSA ALARMA          32        0.03
4  INCIDENTES EXTERNOS           5        0.00

In [107]:
print(variables_categoricas[5])
print(tabla_frecuencias(df,variables_categoricas[5]))

tipo_entrada
          categoria  frecuencia  porcentaje
0   LLAMADA DEL 911      111287       89.56
1  BOTÓN DE AUXILIO        6998        5.63
2             RADIO        5312        4.27
3            CÁMARA         332        0.27
4             REDES         191        0.15
5       APLICATIVOS         126        0.10
6    LLAMADA APP911          15        0.01

In [108]:
print(variables_categoricas[6])
print(tabla_frecuencias(df,variables_categoricas[6]))

alcaldia_cierre
                 categoria  frecuencia  porcentaje
0               Iztapalapa       20197       16.25
1        Gustavo A. Madero       13850       11.15
2               Cuauhtémoc       12911       10.39
3      Venustiano Carranza        9229        7.43
4                 Coyoacán        9111        7.33
5                  Tlalpan        9070        7.30
6            Benito Juárez        8917        7.18
7           Álvaro Obregón        8481        6.83
8           Miguel Hidalgo        7673        6.17
9                Iztacalco        5989        4.82
10            Azcapotzalco        5188        4.18
11              Xochimilco        4831        3.89
12                 Tláhuac        3656        2.94
13   Cuajimalpa de Morelos        2333        1.88
14  La Magdalena Contreras        1948        1.57
15              Milpa Alta         869        0.70

# Numéricas

In [92]:
df.columns

Index(['folio', 'fecha_hora_creacion', 'fecha_hora_cierre',
       'tipo_incidente_c4', 'incidente_c4', 'alcaldia_inicio', 'codigo_cierre',
       'clas_con_f_alarma', 'tipo_entrada', 'alcaldia_cierre',
       'alcaldia_catalogo', 'colonia_catalogo', 'longitud', 'latitud', 'largo',
       'cordenada_fuera_cdmx', 'hora', 'dia', 'mes', 'año', 'dia_semana'],
      dtype='str')

In [109]:
numericas = ['latitud', 'longitud', 'tiempo_minutos']

display(df[numericas].describe().round(2).T)
display(df[numericas].isna().sum().to_frame('faltantes'))

,count,mean,std,min,25%,50%,75%,max
latitud,124261.0,19.38,0.07,19.09,19.33,19.38,19.43,19.63
longitud,124261.0,-99.13,0.06,-99.35,-99.17,-99.14,-99.09,-98.95
tiempo_minutos,124261.0,263.64,300.42,0.38,184.15,187.65,191.43,4600.17

                faltantes
latitud                 0
longitud                0
tiempo_minutos          0

# Valores extremos (regla del rango intercuartílico)

In [110]:
q1 = df[numericas].quantile(0.25)
q3 = df[numericas].quantile(0.75)
iqr = q3 - q1

extremos = ((df[numericas] < q1 - 1.5 * iqr) |
            (df[numericas] > q3 + 1.5 * iqr)).sum()

extremos

latitud             515
longitud           1127
tiempo_minutos    31073
dtype: int64

# 3. Variables Temporales

Se identifica el periodo cubierto, el número de meses con registros y la distribución mensual.

In [111]:
fechas = ['fecha_hora_creacion', 'fecha_hora_cierre']
df[fechas] = df[fechas].apply(pd.to_datetime, errors='coerce')

resumen_fechas = pd.DataFrame({
    'fecha_minima': df[fechas].min(),
    'fecha_maxima': df[fechas].max(),
    'faltantes': df[fechas].isna().sum()
})
display(resumen_fechas)

                           fecha_minima        fecha_maxima  faltantes
fecha_hora_creacion 2021-12-31 20:59:59 2024-02-29 20:53:56          0
fecha_hora_cierre   2022-01-01 00:04:09 2024-02-29 23:58:48          0